basic.forever(function () {
    basic.showString("Maciek")
    basic.showIcon(IconNames.Ghost)
    basic.pause(100)
    basic.showNumber(3)
    basic.pause(100)
    basic.showNumber(2)
    basic.pause(100)
    basic.showNumber(1)
    basic.pause(100)
    basic.showNumber(0)
    basic.pause(100)
    basic.showString("Witaj na seansie PANDA3")
})
