def on_forever():
    basic.show_string("Maciek")
    basic.show_icon(IconNames.GHOST)
    basic.pause(100)
    basic.show_number(3)
    basic.pause(100)
    basic.show_number(2)
    basic.pause(100)
    basic.show_number(1)
    basic.pause(100)
    basic.show_number(0)
    basic.pause(100)
    basic.show_string("Witaj na seansie PANDA3")
basic.forever(on_forever)
